### ISSUE TITLE
Timing issue with tests

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#117]
Regarding our discussion [here](https://github.com/yisar/fre/commit/cbbab3ba986f4b369f4e25367dcfa84fcb8b395a#r36382266), there is a still a timing issue of some sort with the tests.

> Yes, `lastState` exists, but `stateNumber` console twice when `stateNumber===1`. I don't know why it executes twice, but this is the reason for the tes

It doesn't run twice for `stateNumber===1` - I was able to [change it back](https://github.com/yisar/fre/compare/master...mindplay-dk:fix-reconciliation-test) without problems and the test still runs green... it's what I mentioned earlier - there is some kind of timing issue still, and somehow, calling `console.log` at the right moment fixes the problem.

So `console.log` somehow has side-effects affecting the timing here - I don't have an explanation, but it's completely repeatable: remove the `console.log` statement and the test fails - leave it in there and it passes. This is a real JavaScript moment. I can feel my brain melting. 😶

**Comment by yisar** [comment]
I suspect this is a unique bug of jest. `console.log` is a time-consuming behavior, which plays a role of delaying time.

Unfortunately, I can't find the reason of it. We temporarily hack it, and then spend some time waiting for the reason to be revealed

**Comment by mindplay-dk** [comment]
> I suspect this is a unique bug of jest.

I wouldn't be surprised. 🙄

**Comment by yisar** [comment]
> I wouldn't be surprised. 🙄
Is tape better about here?
I have no experience with this, many test frameworks, I do n’t know which is better😭

**Comment by mindplay-dk** [comment]
> Is tape better about here?

Well, tape is simple - I wouldn't know where to start debugging this issue with Jest, because it's a huge code base with many external dependencies.

But I suspect we're running into some unlucky combination of subtle bugs in JS-DOM and Jest... some of the behavior we're testing (queue and scheduler) is very sensitive to precise browser scheduling behavior and the event-loop - remember this?

https://github.com/yisar/fre/blob/04ab1c108fc9dd4c24de1ce7e7a33239502868b0/src/scheduler.js#L85-L93

We're not even testing with the real browser-specific code here - so even if these tests did pass, we don't know if they would pass in the browser with a proper browser-specific implementation of that function.

Maybe we should think about moving the tests to a proper headless browser?

We probably should do that under any circumstances to get a more realistic test.

I'd like to get rid of Jest either way - it's just too complex and slow...

**Comment by yisar** [comment]
Based on your suggestions, I read the tape's documentation carefully, and I like his simplicity. 
I changed my mind, we can change to tape and learn to use it together😊

**Comment by mindplay-dk** [comment]
Let's leave this issue here until we see if `tape` changes anything.

**Comment by yisar** [comment]
https://github.com/yisar/fre/tree/master/test

Good news, according to your suggestion, I will switch the test suite to playwright-test, and use zaro to rewrite them. Now it is particularly fast and accurate. Thank you!
