### ISSUE TITLE
styled-components support

### ISSUE THREAD

**Issue by justinushermawan** [yisar/fre#143]
Is it possible to use styled-components in fre?

**Comment by yisar** [comment]
Hello, thank you for your issue

I think it's possible to use styled component in fre, but I haven't tried it.

In the past, I used to use goober in fre. Here is a [demo](https://codesandbox.io/s/fre-goober-ffqjv), which is similar to use and may help you.

**Comment by justinushermawan** [comment]
@yisar Yes I think it's already close to what I need right now. Thank you.
