### ISSUE TITLE
cant open website

### ISSUE THREAD

**Issue by Akimotorakiyu** [yisar/fre#191]
![图片](https://user-images.githubusercontent.com/31165554/102221796-8bfac100-3f1d-11eb-845a-cf6e373de06d.png)

**Comment by yisar** [comment]
这个网址俺好久木有管啦，我还在写 fre2，等写完再搞搞的

**Comment by Akimotorakiyu** [comment]
> 这个网址俺好久木有管啦，我还在写 fre2，等写完再搞搞的

OK! 先关掉了！
