### ISSUE TITLE
reconsiler.ts file has some spelling mistake

### ISSUE THREAD

**Issue by eward957** [yisar/fre#193]
-------
## insertPont? 

https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/reconciler.ts#L128
https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/reconciler.ts#L140
https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/reconciler.ts#L146
https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/reconciler.ts#L156

-------
##  BUT:  insertPoint was defined by IFiber interface,and was used by commit function

https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/type.ts#L55
https://github.com/yisar/fre/blob/5a9d05eea97deaf0159d732edd2598859b207f06/src/reconciler.ts#L203

**Comment by yisar** [comment]
This is my mistake, I'm sorry, because `fre-next` is still in the prototype stage, I can only continue on Saturday and Sunday, maybe you can create a pr, let's complete it together?

**Comment by yisar** [comment]
I fixed the spellings, but will continue until all tests passed.

**Comment by eward957** [comment]
> I'm sorry,  i just saw it right now :(
