### ISSUE TITLE
component not support render array

### ISSUE THREAD

**Issue by timeTravelCYN** [yisar/fre#199]
```javascript
function App(){
  return { for(arr) }
}

function for(arr){
  return arr
}
```

**Comment by yisar** [comment]
Thanks, I guess it can be dealt with in the H function, maybe.

**Comment by yisar** [comment]
Look at here:  https://github.com/yisar/fre/pull/202

Component must have a root-elment, this will improve performance.

Render array and fragment are no longer supported.
