### ISSUE TITLE
[typescript] publish type declarations file

### ISSUE THREAD

**Issue by hyrious** [yisar/fre#205]
Although your package.json has `"typings": "dist/types/index.d.ts",`, there is no such file.

Add an extra build step `tsc -p src -d --emitDeclarationOnly --outDir=dist/types` before release.

As a workaround, I put it in global script and add such `global.d.ts`:

```ts
export {};

declare global {
    var fre: typeof import("fre/src");
}
```

**Comment by yisar** [comment]
Thanks!

**Comment by yisar** [comment]
竟然不是pr😭快来一个

**Comment by hyrious** [comment]
> 竟然不是pr😭快来一个

这就来 :+1:
