### ISSUE TITLE
1kb?

### ISSUE THREAD

**Issue by jantimon** [yisar/fre#216]
here it says 2.4kb not 1kb:
https://bundlephobia.com/result?p=fre@2.0.0-rc8

**Comment by yisar** [comment]
In fact, after tree-shaking helloworld project can achieve 1kb.  1kb is our goal, but the premise is not to sacrifice readability.

**Comment by yisar** [comment]
I have to say that in the past, the algorithm of fre1 can achieve 1kb, but for fre2, I reimplemented the reconciliation algorithm, and it can’t go back to 1kb. Maybe we have to compromise on the size, 2kb is also small.

**Comment by jantimon** [comment]
I guess that's fine than :)
So all we need to do is to upgrade the readme

**Comment by yisar** [comment]
The readme has been changed, close the issue first, until we come back.
