### ISSUE TITLE
使用多个useState导致页面错乱

### ISSUE THREAD

**Issue by a145789** [yisar/fre#225]
`function App() {
  const [up, setUp] = useState(0)
  const [down, setDown] = useState(0)
  return (
    <div>
      <h1>{up}</h1>
      <button onClick={() => setUp(up + 1)}>+</button>
      <h1>{down}</h1>
      <button onClick={() => setDown(down - 1)}>-</button>
    </div>
  )
}`

点击 setUp 按钮会使 down 数据错乱

**Comment by yisar** [comment]
修复啦，阿里嘎多
