### ISSUE TITLE
Cannot create property 'tag' on string

### ISSUE THREAD

**Issue by oleggrishechkin** [yisar/fre#244]
Hi, i want to try fre in js-framework-benchmark, but I get error - "Cannot create property 'tag' on string ..."

version:

"fre": 2.0.1

```javascript
import { render  }  from "fre";

render(
    <div className="col-md-6"><h1>React Optimized</h1></div>,
    document.getElementById("main")
);
```

babel:

```javascript
{
    presets: ['@babel/preset-env'],
    plugins: [[
        '@babel/plugin-transform-react-jsx',
        {
            runtime: 'automatic',
            importSource: 'fre',
        },
    ]]
}
```

First text node throw this error

(error throw on this line - https://github.com/yisar/fre/blob/master/src/reconciler.ts#L142)

**Comment by yisar** [comment]
It seems that the H function is not suitable for Babel's jsx2 parsing. Before adjusting the H function, you can use the jsx1:

```js
{
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "h",
        "pragmaFrag": "Fragment"
      }
    ]
  ]
}

```

**Comment by yisar** [comment]
Here is a benchmark example
https://github.com/yisar/fre/blob/master/demo/src/benchmark.tsx

**Comment by oleggrishechkin** [comment]
Thanks, with pragma it's work. But i get some other errors (and also performance was terrible). I will try your benchmark code

**Comment by yisar** [comment]
> and also performance was terrible.

For this test, create 10000 rows will broken. This is because I used recursion in the commit phase, and other cases are not bad.

I plan to give up recursion in the future and go back to linked list again. Do you have any good ideas?

**Comment by oleggrishechkin** [comment]
@yisar Sorry, I don't know how it works, but i check source code and see you use some array methods like forEach some and other, may be i am wrong, but i think for loop works faster. You also call functions like same, isFn and other, but if you call this functions body directly it may increase performance.

**Comment by yisar** [comment]
@oleggrishechkin The details you mentioned will be what fre2 will do next.

However, we have to say that fre is a little slower than other frameworks in performance testing. There is another important reason:
https://github.com/yisar/fre/blob/master/src/reconciler.ts#L49

Fre's rendering is asynchronous, it will be interrupted every 16 ms(Time slicing), so the overall rendering time will be more

But in exchange for better response performance, the browser won't block during rendering.

So in general, we can do two things in the future to improve performance:

1. Optimize JS details, make good use of VM, and improve JS execution speed.
2. Find an heuristic slicing algorithm, better time slicing, for example, when the CPU is not tight, do not slice.

This is what fre2 needs to do.

**Comment by yisar** [comment]
![微信图片_20210606191240](https://user-images.githubusercontent.com/12951461/120924081-7adc8100-c704-11eb-9fe7-fb936218fa35.png)

I refactor the algorithm again, and then used a new technique called `centralized paints`

This is a technology similar to `DocumentFragment`. It operates DOM in memory and finally paints to the screen at final time.

Now fre is super fast, even faster than vanilla js.

**Comment by yisar** [comment]
It seems that the problem here has been solved, I will close it first
