### ISSUE TITLE
请添加 eslint 约束代码格式

### ISSUE THREAD

**Issue by SyMind** [yisar/fre#270]
请添加 eslint 约束代码格式

**Comment by yisar** [comment]
我不喜欢 eslint 这类工具，可以加一个 pre-commit 的自动格式化命令

**Comment by SyMind** [comment]
你不喜欢 eslint 的理由是什么？

**Comment by yisar** [comment]
1. 编译速度太慢，影响调试
2. 我个人对代码有很多偏好，不想屈服 lint 工具
3. 现在已经没人用 eslint 了，大家至多加了一个统一格式化，比如 deno fmt

**Comment by SyMind** [comment]
我可以尊重你的偏好，但是多人协作时代码风格不统一的问题还是需要解决的。

**Comment by yisar** [comment]
加一个 fmt 就可以，以前有的，换 ts 给删了……

**Comment by SyMind** [comment]
233

**Comment by yisar** [comment]
https://github.com/yisar/fre/blob/1.13.5/package.json#L17

我对 ts 简直了……惨不忍睹，之后整理下类型，再考虑再换回来吧
