### ISSUE TITLE
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by yangzhaox** [yisar/fre#301]
Hi @yisar,

Your project looks interesting, so I tried to migrate a Preact project to Fre but encountered an issue. To reproduce, I setup a tiny project [fre-test ](https://github.com/yangzhaox/fre-test.git). If you are using VSCode, right click the index.html and select 'Open with Live Server'. After 2 seconds, you'll see the error in browser console:
```
fre.js:1 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at E (https://unpkg.com/fre@2.3.3/dist/fre.js:1:1660)
    at https://unpkg.com/fre@2.3.3/dist/fre.js:1:2214
    at S (https://unpkg.com/fre@2.3.3/dist/fre.js:1:2259)
    at n (https://unpkg.com/fre@2.3.3/dist/fre.js:1:2093)
    at y (https://unpkg.com/fre@2.3.3/dist/fre.js:1:1364)
    at https://unpkg.com/fre@2.3.3/dist/fre.js:1:1115
    at Array.forEach (<anonymous>)
    at MessagePort.e (https://unpkg.com/fre@2.3.3/dist/fre.js:1:1104)
```
Look forward to your response. :-)

Best,
Yang

**Comment by yisar** [comment]
It seems that this is a bug. You can temporarily use null instead of empty string. I will fix it this weekend.

```js
const backHomeButton = canBackHome ? html`<div>
        <button type="button">Click Me!</button>
    </div>` : null
```

**Comment by yisar** [comment]
fixed this, thanks!
