### ISSUE TITLE
useState bug

### ISSUE THREAD

**Issue by yangzhaox** [yisar/fre#302]
Hi @yisar,

When migrating from Preact to Fre, I discovered another issue which can be reproduced in the branch : [state-bug](https://github.com/yangzhaox/fre-test/tree/state-bug).

Using VSCode, right click the index.html and select 'Open with Live Server'. Click 'finish' button, 'Click Me!' button appears right away. It should appear after 5 seconds. 

I had a quick look, seems canBackHome state (line 14) is assigned the value of title state (line 8).

Best,
Yang

**Comment by yisar** [comment]
I temporarily fixed it in 2.3.4.
