### ISSUE TITLE
Fragment子节点错位

### ISSUE THREAD

**Issue by E478** [yisar/fre#316]
```js
import {render, h, Fragment, useState, useEffect} from './fre'

function fk({i = 0}) {
	const [c, s] = useState(i);
	return h('button', {
		onClick() {
			s(c + 1);
		}
	}, c);
}

function test() {
	const [c, s] = useState(true);
	return h(Fragment, {}, h('button', {
		onClick() {
			s(!c);
		}
	}, 'change'), c ? h(fk) : 'none');
}

render(
	h(test),
	document.getElementById('app')
);
```

![image](https://user-images.githubusercontent.com/5538159/137662436-b8862dd8-65ff-4519-a562-4e4a947310c3.png)

点击change之后子节点会错位

![image](https://user-images.githubusercontent.com/5538159/137662462-ec4ea491-b94a-41c2-9408-d344ab144438.png)
![image](https://user-images.githubusercontent.com/5538159/137662474-371830ee-5f4c-469a-ab3e-0f532d3680cf.png)

把Fragment换成'div'就没有问题了，Fragment多于两个child好像也没问题。。。很玄学

不知道是否是我使用方式有问题？

**Comment by E478** [comment]
😂😂写好了

**Comment by yisar** [comment]
我周六日看呗，现在还在班上o(╥﹏╥)o

**Comment by E478** [comment]
> 看一下 getParent 方法，理论上 fragment 也得有 parentNode

getParent本身没有问题，fragment也确实有parentNode，但就是因为真实parent节点就得是那个div……在浏览器DOM Tree里面实际上是
```html
<div>
 C1
 C2
 C3
</div>
```
毕竟也没办法在最后commit时，拿一个虚空节点作为parentNode去insertBefore。。。

对映到真实DOM树时，某个Node底下的childNodes只有一部分需要update，
这个时候就会有Node不知道该往哪insertBefore了（例子中，在Fragment组件setState后，reconcile遍历时不会遍历到C3，只会在Fragment子树下对C2和C1进行遍历）



（总之没想到Fragment这么蛋疼……怪不得React很久才推出Fragment
当然很多时候用<div style={{display: 'contents'}}>也能代替……
