### ISSUE TITLE
useState and useReducer dispatch unstable between renders

### ISSUE THREAD

**Issue by kavika-1** [yisar/fre#331]
Using a library that works in React/Preact, but not in fre.  Upon debugging, saw this code:
````
  const [embla, setEmbla] = useState<EmblaCarouselType>()
  ...
  useEffect(() => {
  ... setEmbla(...)
  }, [..., setEmbla])

````
The `useEffect` gets triggered unexpectedly, which is any time the function component (re)renders.  It appears to be due to `setEmbla` being assigned a new function, thus triggering the `useEffect` again.  Understandable why the library writers did this, since rules of hooks requires adding anything used in the `useEffect` to be declared in the dependencies array.

Does it make sense to address this?

https://github.com/yisar/fre/blob/master/src/hook.ts#L31

**Comment by yisar** [comment]
https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.new.js#L1515

Maybe it's meaningful. I don't see that react has additional processing here. Can you write a demo use case? Let me see the specific situation first.

**Comment by yisar** [comment]
Thank you. I fixed it. `setState` should only be initialized once.
Please update `2.4.5`

**Comment by kavika-1** [comment]
I can confirm that the actual real component(s) now work as well.  That's incredible turn-around time 👍 🥇  Thank you!
