### ISSUE TITLE
What is the options object for?

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#48]
The `reconciler` module exports an `options` object - can you explain what these options are for?

1. There's a few check for `options.end` in the `reconciler` itself, but I don't see any code (in either `src` or `demo`) that actually sets `options.end`?

2. There's an `options.commitWork` callback, which seems to completely [override](https://github.com/132yse/fre/blob/4545e3abc160195f90af6a6c7b0f754a2eab66c3/src/reconciler.js#L40-L42) the built-in `commitWork()` function in the `reconciler` - it's [being set](https://github.com/132yse/fre/blob/4545e3abc160195f90af6a6c7b0f754a2eab66c3/demo/commitWork.js#L14-L16) only in one of the demos, where it just does a `console.log()`.

3. There's an `options.platform` value [being set](https://github.com/132yse/fre/blob/4545e3abc160195f90af6a6c7b0f754a2eab66c3/demo/commitWork.js#L13) in the same same, which doesn't appear to be used anywhere.

What was the idea with (these) options?

Maybe it's left over from early development or something?

**Comment by 132yse** [comment]
Well, I'm trying to explain.
Options is a method that we implement externally and then can override the same name within fre.
```js
options.end = true
```
It means crossing end. some DOM operations can be ignored.
Then on the other side, implement the corresponding logic, such as React Native.

I rewrote `commitWork` for [Fard](https://github.com/132yse/fard/blob/master/packages/fard/index.js#L9)
You can think of it as the Chinese mini React Native. 
It can run fre reconciliation algorithm to other no-dom environments.

So far, only these two have been set:
```js
options.end = true
options.commitWork = fiber =>{
    //rewrite for no-dom end
}
```
If you need to rewrite other methods, you can refer to it.

**Comment by 132yse** [comment]
I have a idea to turn on synchronous rendering. Such as :
```
options.sync? workloop(): defer(workloop)
```
I'll refactor this part tomorrow to support synchronous rendering.
What do you think?

**Comment by 132yse** [comment]
I'm sorry I need to go to bed now because of jet lag. I'll continue tomorrow~

**Comment by 132yse** [comment]
I'm sorry I misplaced it.
