### ISSUE TITLE
Add support for callback refs?

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#62]
What do you think about adding support for [callback refs](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)?

**Comment by 132yse** [comment]
It shouldn't be difficult. I'll support it right away.

**Comment by 132yse** [comment]
Now it's supported 😀

**Comment by mindplay-dk** [comment]
Let's leave this issue open for now, as a reminder to add a test.

**Comment by 132yse** [comment]
> Let's leave this issue open for now, as a reminder to add a test.
👌

**Comment by yisar** [comment]
We already have tests about refs [here](https://github.com/yisar/fre/blob/master/test/ref.test.js), I'll close it first.
