### ISSUE TITLE
Errors get silenced?

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#84]
If an error occurs, for example, while executing a hook, it looks like the error gets silenced? You don't see an error on the console, or anywhere.

I think I've run into this a number of times while writing tests - many times I've had `jest` hanging for several minutes before finally reporting a timeout, with no real clue why this was happening... An actual exception getting throw would cause `jest` to halt - but instead, you have to wait for every test to time out, which can take a long time.

I'm also now running into this in my [Component example](https://codesandbox.io/s/fre-component-i6sbs) - I had forgotten to declare `App.componentDidMount` and the effect in `useComponent` was attempting to call this... Instead of an error on the console, all the buttons simply stopped worked - there was no way to see why.

I've been suspecting this had something to do with `flushWork`, so I made a quick change:

```js
function flushWork(iniTime) {
  try {
    return workLoop(iniTime)
  } catch(e) {
    console.error(e)
  } finally {
    currentTask = null
  }
}
```

This revealed the error on the console! So far so good.

But this is just printing an error-message now, so this still wouldn't fix the problem under `jest`, since `console.error` just prints an error-message but doesn't work like an exception - so `jest` still won't know it happened.

I also tried something like this:

```js
function flushWork(iniTime) {
  try {
    return workLoop(iniTime)
  } catch(e) {
    throw e // <-- re-throwing the error
  } finally {
    currentTask = null
  }
}
```

But that also just silences the error. 🤨

It's weird, because `try/finally` without a `catch` isn't suppose to handle errors at all - so if you do [this](https://jsfiddle.net/mindplay/pts5Lurd/1/):

```js
function flurp() {
  throw "UGH";
}

try {
  flurp()
} finally {
  console.log("NP!")
}
```

You will see the error-message for the exception, as expected.

I can't figure out why it behaves differently in `fre`... 🤷‍♂️

(I also suspect this could be related to the problem with the browser stalling, as mentioned on Twitter - if it keeps running through the work-loop trying to complete the same task, but an error prevents it from ever finishing the next task in the queue? Just a guess.)

Any ideas?

**Comment by 132yse** [comment]
I see no error handling in other frameworks, such as hyperapp.
I think maybe fre needs a mechanism to deal with errors because it has too many border errors.

**Comment by 132yse** [comment]
For the problem from twitter, I don't know why up to now. So sad…

**Comment by mindplay-dk** [comment]
This isn't a request to add error-handling. (although that's interesting.)

For the moment, I'm trying to figure out why errors get *silenced*... when there's an error in an effect right now, you can't see it, not on the console, not anywhere - it just gets ignored and, for example, a click-handler, has no effect at all.

Here's a sandbox to demonstrate the problem:

https://codesandbox.io/s/fre-demo-uxuic

As you can see, I've deliberately broken the `increment` event-handler.

Under normal circumstances, you would see an error in the console when attempting to call a function that doesn't exist - but here, nothing...

**Comment by 132yse** [comment]
Wow, I've found the problem we found on twitter, which may be a bug in our current scheduler

Now I've modified the scheduler, which effectively eases the problem.

React's approach is that when the task exceeds a certain number, it will automatically become synchronous rendering, and the UI will be blocked again.

**Comment by 132yse** [comment]
Now it seems that we can support it without any internal modification!

Maybe we can publish a `@fre/component` package?

or `fre/compoent` like `preact/hooks`?

**Comment by yisar** [comment]
Now here is a catchError handler : https://github.com/yisar/fre/blob/master/src/reconciler.ts#L69

**Comment by mindplay-dk** [comment]
> Now here is a catchError handler

But this will still silence errors by default?

This was not a request to add error handling - as said:

> For the moment, I'm trying to figure out why errors get silenced... when there's an error in an effect right now, you can't see it, not on the console, not anywhere - it just gets ignored and, for example, a click-handler, has no effect at all.

If errors are silenced by default, how am I supposed to know when there's a bug in my code? Not all code produces something on the screen that you could notice is missing - and even if it did, suppressing errors makes it very difficult to guess the source of the error.

**Comment by yisar** [comment]
@mindplay-dk Errors should not be silenced, but I need particles to be able to `try catch` in the right place
