### ISSUE TITLE
Scheduler queue issue

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#94]
It looks like there's a problem with the queue.

With the [benchmark](https://github.com/krausest/js-framework-benchmark/compare/master...mindplay-dk:fre-keyed), try clicking *quickly* on several buttons, for example:

* "Create 10,000 rows"
* "Update every 10th row"
* "Update every 10th row"
* "Update every 10th row"
* "Swap rows"
* "Swap rows"
* "Swap rows"

Because the async renderer leaves time-slices open for UI interaction, users can actually click on buttons (etc.) to trigger calls to (for example) a `useState`-setter function, while the reconciler is still working.

Presumably, additional updates should go into the queue, and any additional updates should go to the back of the queue and run later?

My guess is, it ends up trying to "start" the work-loop twice?

(I suspect this might also be a problem for projects with more than one render-root - e.g. with more than one call to `render` call for independent UI areas on a single page...)

**Comment by 132yse** [comment]
One page can only have one scheduler. When there are multiple roots, it will enter taskqueue to sort with dueTime.

**Comment by XN333** [comment]
我寻思这个小和尚老爱搁群里装逼是不？一件群发装逼，真几把涩会，你说你麻痹要真分享技术也就罢了，一句话10个字你可以9个字都是你吗的专业英文名词，你麻痹一通专业名词组句呢我寻思。

**Comment by yisar** [comment]
@XN333 秀啊

**Comment by XN333** [comment]
净整你吗一些花里胡哨虚的东西  自己能整明白不 就拿出来装了 搞就搞点有用的行不 我寻思老二刺猿就这？

**Comment by XN333** [comment]
来对线  麻痹的二刺螈技术宅不是很踏马牛来着

**Comment by KHatsuneMiku** [comment]
操你妈的二次元恶心人是吧，幼稚的动画片几把不看，几把天天群里发发发你吗发发发发，孤儿没爹没妈是不是想在群里找个？

**Comment by yisar** [comment]
@KHatsuneMiku @XN333 有事到别处说，在开源项目底下瞎bb是很没有教养的行为

**Comment by XN333** [comment]
赶紧继续发朋友圈求安慰啊fw东西，真不知道一天天的整这些花里胡哨有什么用，整就算了还到处装比这我真忍不了？我寻思我整俩基础题你也做不出来啊，你搁这天天整些虚的，你咋不直接去造火箭呢，弟弟
