### ISSUE TITLE
Missing clean-up of refs

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#97]
It looks like neither callback refs nor object refs are getting cleaned up.

In the case of callback refs, this means you can't use a callback to clean up any side-effects - here's an example:

```jsx
const DatePicker = () => {
  const init = el => {
    if (el) {
      // initialize date-picker using some third-party plain JS lib...
    } else {
      // clean up any date-picker pop-ups that may still be open...
    }
  }
  return <span ref={init}/>
}
```

The clean-up call never happens, so we currently can't really rely on refs for this sort of thing.

Note that this may not be a very useful feature in a codebase that exclusively uses hooks, but if we want to support class-based components at some point down the line, many class-based libraries rely on refs for side-effects and clean-up.

I noticed earlier that object refs also do not get cleaned up - so if you have something like this:

```jsx
const Component = () => {
  const item = useRef()
  const [showItem, setShowItem] = useState(true)

  // ...

  return (
    <div>
      {showItem && <div ref={item}/>}
    </div>
  )
}
```

If `showItem` gets updated to `false`, `item.current` will still point to the DOM element, which gets removed from the DOM, but now it can't be garbage-collected.

As always, I also compared the behavior with `preact`, and it also deviates from `react` on this point, so I have opened an issue [here as well](https://github.com/preactjs/preact/issues/2052).

As explained in that issue, I am not actually sure if what I reported there is a bug in `preact` or `react`, since `preact` appears to behave more accurately as it's described in the React docs.

Until we know if the behavior regarding `null` updates is correct in `react` or `preact`, I would actually advise you *wait* to address this issue - there is definitely an issue in `fre` either way, since it doesn't remove references at all, but at the moment I couldn't tell you precisely if `react` or `preact` dispatches the `null` updates correctly, so lets wait and see.

For comparison, here's the output from all three:

![image](https://user-images.githubusercontent.com/103348/67673665-e8e29300-f97a-11e9-910c-9ee2cd8ead8f.png)

Note that, besides the missing `null` updates, it also looks like callback refs are also currently being dispatched *twice* during every update in `fre`.

It could be you actually meant for one of those calls to be the `null` update after clearing out the internal reference? That would seem to bring the behavior very close to that of `react` as it behaves currently.

You might to address that detail right away, as well as the `null` updates missing after removal.

Or just wait and see who's right between `react` and `preact` first. 😏

**Comment by 132yse** [comment]
Well, I stare at it.
But we don't have to be unified with react or preact. Maybe we can find a better answer.

**Comment by mindplay-dk** [comment]
> But we don't have to be unified with react or preact. Maybe we can find a better answer.

Maybe, but as explained, refs are often used in conjunction with side-effects, and side-effects frequently require clean-up.

`fre` of course is "hooks only", so we can work from a different set of assumptions than `react` - but I think we need to do at least what `preact` does in terms of `null` updates - otherwise clean-up is impossible and garbage-collection won't work.

**Comment by mindplay-dk** [comment]
Here's a [preliminary test](https://github.com/132yse/fre/compare/master...mindplay-dk:test-callback-refs) with a TODO that can't be addressed until we know the reason why `react` and `preact` deviate on this point.

**Comment by mindplay-dk** [comment]
Okay, it looks like we [have our answer](https://github.com/preactjs/preact/issues/2052#issuecomment-547067083) with regards to `react` behavior:

> It’s intensional because it’s a new function identity we don’t know if it’s a different ref all together.

It took me a minute to wrap my head around that - but consider the difference between this:

```jsx
const Component = () => (
  <div ref={ div => doSomething(div) }/>
)
```

And this:

```jsx
const ref = div => doSomething(div)

const Component = () => (
  <div ref={ ref }/>
)
```

In the second case, `ref` points to the same value every time `Component` is called.

But in the first case, when `Component` runs, the `div => doSomething(div)` expression evaluates every time and generates a new function with a new identity.

That is, `(div => doSomething(div)) === (div => doSomething(div))` would be `false`.

I guess, if you have a *pure* function, you can micro-optimize by turning it into a global `const`, so that the reconciler can see they haven't changed.

Regardless of that possible optimization, what I found appears to be a subtle bug in `preact` - so `react` is actually making the correct number of calls to `ref` functions.

I updated the sandbox and added numbered function instances (e.g. `[#1]`) to better illustrate the problem.

So here's a side-by-side comparison between `react` and `fre`:

![image](https://user-images.githubusercontent.com/103348/67756107-b186eb80-fa39-11e9-8d54-fb45e3a219cc.png)

So it's actually close to `react`, just that:

1. Refs are getting called twice, e.g. with elements instead of nulls during the same update. (this would duplicate any side-effects.)

2. Null updates missing at the time of removal. (refs with side-effects would be unable to clean up.)

3. Effect hooks are being called too soon. (refs must run before effects - whether these are functional refs or memoized `{ current }` objects, we need to establish the reference first, since the effect might operate on that reference.)

Make sense?

**Comment by 132yse** [comment]
Thank you very much. I think this problem and #87  should exist at the same time. I will fix them as soon as possible 💯 .

**Comment by 132yse** [comment]
Hello, I'm sorry I took a break
To solve this issue, I have some questions, such as:
```js
function App () {
  return (
    <div>
      <p ref={t}>will I update?</p>
    </div>
  )
}
```
When the `<App/>` is removed, will its children be updated, such as the `<p><p/>` here?

**Comment by mindplay-dk** [comment]
> When the `<App/>` is removed, will its children be updated, such as the `<p><p/>` here?

Yes - null updates happen for any refs that were present in the subtree being removed. Imagine using refs to create side-effects - your script has to get the `null` notifications, otherwise they don't know how to clean up after any side-effects.

Look here for Preact's behavior, for example:

https://codesandbox.io/s/fre-demo-uxuic

Try removing a counter and watch the console output.

This is what's marked with "should be nulls" and "missing null updates on removal" in the comparison above.

**Comment by 132yse** [comment]
I don't know how to implement it now, because for the children elements of deleted elements, it will not traverse and update. Is there any other ways?

**Comment by 132yse** [comment]
I have an idea that the child elements are not updated, but cleanup still executes, such as
```js
const DatePicker = () => {
  console.log('update') // not executed
  const init = el => {
    if (el) {
    } else {
      cleanup() // executed
    }
  }
  return <span ref={init}/>
}
```
Is this feasible? 
In fact, I think react's handling of these aspects is too complex. I've been trying to simplify them, but I haven't any good ideas.

**Comment by mindplay-dk** [comment]
Other engines do traverse subtrees during removal, and I don't believe there's any other way? Components, effects and refs all make up the life-cycle, so you can't simply remove them without processing them completely - otherwise, you have a sometimes incomplete life-cycle, which makes the whole thing very unpredictable.

In my opinion, the engine needs to guarantee completeness of the full component life-cycle - otherwise, any global effects will cause major problems.

> I have an idea that the child elements are not updated, but cleanup still executes

Yes, this example is how callback refs are expected to be used.

So you should be able to do something like this:

```jsx
import { initDatePicker, destroyDatePicker } from "some-plain-js-date-picker-library";

const DatePicker = () => {
  const [instance, setInstance] = useState();

  const init = el => {
    if (el) {
      setInstance(initDatePicker(el));
    } else {
      destroyDatePicker(instance);
    }
  }

  return <span ref={init}/>
}
```

In this example, a fictive third-party plain JS date-picker library has a function `initDatePicker` that attaches the date-picker behavior to a given DOM element and returns an instance object, which internally has a reference to the DOM element it's attached to.

Because the date-picker might be popped open when it gets destroyed, the `destroyDatePicker` function may need to clean up a DOM element for the open popup, which it might have injected into the `body` element at the root.

Using callback effects this way only works reliably if we can guarantee a complete life-cycle - if `destroyDatePicker` doesn't get called, for example, when a parent "app" component with multiple date-picker instances gets removed, you can't reliably integrate with third-party libraries without the risk of leaving a dead popup element behind in the `body` element, for example.

**Comment by 132yse** [comment]
It's hard for me to traverse the sub elements of the deleted element, but I can do the same as effect. When the element exists, refs will be collected, and the next time I delete it, cleanup will be executed.

> Other engines do traverse subtrees during removal, and I don't believe there's any other way?

In fact, I always think that over update is the fault of react. I always want to build in `shouldComponentUpdate`, like Vue, to prevent sub element updates.

**Comment by mindplay-dk** [comment]
> It's hard for me to traverse the sub elements of the deleted element, but I can do the same as effect. When the element exists, refs will be collected, and the next time I delete it, cleanup will be executed.

That sounds like a good way to achieve the same thing without traversal! Actually, this sounds better - you're already traversing that version of the tree during reconciliation the first time, so if you can avoid traversing it a second time by merely recording which refs need to be cleaned up, that ought to be both faster and simpler than another traversal of the old tree. 👍

**Comment by 132yse** [comment]
I've refactored refs, and now it works like this:
```js
function App () {
  const t = useRef(dom => {
    console.log(dom) // span
    return dom => {
      console.log(dom) // null
    }
  })
  return flag && <span ref={t}>I will removed</span>
}
```
More like `useEffect`, It can use a function and return a cleanup, and when then element deleted, the cleanup will execute.

**Comment by mindplay-dk** [comment]
Hmm, this may be a somewhat confusing deviation from React?

What's the point of the `dom` argument to the clean-up function? It will always be `null`, won't it? So there's no reason for it to receive any argument at all.

I'm not sure this is a good idea - especially if we proceed with the `Component` class API, this would make it more difficult to port existing code from React.

I like the idea though - in a library that is *hooks first*, this is more consistent with the concept from hooks.

Could we make both work?

```
function App () {
  const t = useRef(dom => {
    console.log(dom) // span or null
  })
  return flag && <span ref={t}>I will removed</span>
}
```

I think all you'd have to do is take the return-value from the function passed to `useRef` and auto-generate a clean-up function, e.g. add `|| () => ref(null)` when storing the clean-up function?

Keep in mind, there are some cases where you *don't* have to do any real clean-up - where the only thing being cleaned up is the DOM element reference for garbage collection purposes, and in those cases, this is more convenient:

```
function App () {
  const [dom, setDom] = useState();
  // ...
  return <span ref={ setDom }/>
}
```

That is, you can use the setter directly as the `ref` function without generating another function.

What do you think?

**Comment by 132yse** [comment]
> Could we make both work?
Maybe we can. But where is the cleanup function? You mean like this?
```js
function App () {
  const t = useRef(dom => {
    if(dom == null){
      cleanup()
    }
  })
  return flag && <span ref={t}>I will removed</span>
}
```
I think the return function is better, Because when we don't need cleanup, we can not return anything.
> you can use the setter directly as the ref function without generating another function.
```js
const t = useRef(setDom)
return <span ref={ t }/>
```
It's convenient, isn't it?

**Comment by mindplay-dk** [comment]
> where is the cleanup function?

In my example, `setDom` works both as the function that accepts the DOM element, and at the same time works as the clean-up function - because all the clean-up function needs to do in this case, is clear the DOM element reference (for garbage collection) which the setter will do when called with `null`.

Not all use-cases have side-effects beyond the DOM element itself - in those cases, there's nothing else to clean up except the reference to the DOM element, which has already been removed from the DOM, so the browser can free memory.

**Comment by 132yse** [comment]
> Not all use-cases have side-effects beyond the DOM element itself
If don't need to clean up, you don't need to return anythis. such as this:
```js
function App () {
  const t = useRef(dom => {
    doSomething()
  })
  return flag && <span ref={t}>I will removed</span>
}
```
Return a function only if cleanup is required

**Comment by 132yse** [comment]
I've refactored refs again, and now, as you say, it's used like this:
```js
function App () {
  const t = useRef(dom => {
    if(dom){
      doSomething()
    }else{
      cleanup()
    }
  })
  return flag && <span ref={t}>I will removed</span>
}
```
Now it doesn't need the return function, but it still needs the wrapped by `useRef`.

**Comment by 132yse** [comment]
I've refactored it again and again. Now it's the same as react, but it won't update children elements:
```js
function App () {
  const t = dom => {
    if(dom){
      doSomething()
    }else{
      cleanup()
    }
  }
  return flag && <span ref={t}>I will removed</span>
}
```

**Comment by mindplay-dk** [comment]
I re-tested the sandbox, and now refs aren't getting cleaned up at all.

And the refs are now called in reverse order.

Also, most of the render tests are currently failing.

![image](https://user-images.githubusercontent.com/103348/68669178-3699f680-054a-11ea-9077-d93cd9e83ad6.png)

**Comment by 132yse** [comment]
I checked your code. The sub elements of deleted elements will not be traversed, so your code is invalid.But It will works like this:
```js
const makeRef = el => {
  if(el){
    console.log('update')
  }else{
    console.log('cleanup')
  }
}
<App ref={makeRef} />
```
Does its sub elements need to perform cleanup?

> Also, most of the render tests are currently failing.

Because of refactoring the effect and ref, I gave up the compatible react , so the current test cases can not works.

I look forward to discussing completely different results from react and modifying the test

**Comment by mindplay-dk** [comment]
I don't understand that example. What element would the `ref` function be receiving here? `<App>` is not an element, it's a functional component, so in React, you would receive the component class instance - but since this library is hooks-only, there are no component classes.

Refs exist primarily to obtain references to DOM elements - with functional components and hooks, this is primarily useful in conjunction with effects, and effects often depend on refs.

> Does its sub elements need to perform cleanup?

Yes, definitely. Refs themselves can have direct effects on the DOM (or other global state) and these types of effects aren't complete without a clean-up cycle - just as `useEffect` would not be very useful if it didn't support clean-up.

> I look forward to discussing completely different results from react and modifying the test

The point of having tests is to define expectations - they're an executable specification of what you intend to build. You can change the tests, if the specification changes, but you need to know why you're changing them; you can't just change the tests to match what the library does, not without knowing precisely what you want the library to do.

<details><summary>I can go into this at length, but it's off-topic to this discussion, so I'll leave the rest of my comments as a collapsible - <em>click here</em>. 🙂</summary>
It's never a good idea to commit changes that break the tests, because you lose track of anything else you might break before you get the tests working again. 

It's a much better idea to change the tests first - this documents the change you'd like to make to the specification, and at that point, you know why the tests are failing and can work towards fixing the code to match the spec.

It's also not a good idea to commit breaking changes directly to `master` - if you're going to change the tests, you should always do so on a separate branch, so the changes to the spec and library can be reviewed and tested together.

I'm not opposed to deviations from React, but you shouldn't be changing (or breaking) the tests unless the requirements have changed. Tests are not an afterthought to show how something works - you should think of them as a plan to show how something *should* work.

In other words, "the test is always right" - if the test fails, it should be because you changed the test, never because you changed the library. (unless you discover that the test itself contains a bug, which does of course also happen.)

This is *not* to say I think my tests are always right! 😉

But since you didn't have any tests, we had to start somewhere, and I'm basing these tests on what I've learned from React, Preact, and a handful of other libraries of this type. If I had merely written tests that matched what your library already did, we wouldn't have found or corrected many of the bugs, so you can probably already see how this works. Again, my tests may not align with *your* expectations, but then you need to describe your expectations with tests before changing the library, otherwise the tests have no real value.

I understand you're new to testing, just trying to help 🙂

[This article](https://www.squash.io/tutorials/what-is-test-driven-development-and-how-to-get-it-right/) summarizes the principles of test-driven development:

> The principles of TDD are as follows:
>
> * Tests are always written before the code that will make them pass. The test anticipates the correct behavior of the code.
> * Development proceeds one test at a time. Once a test goes from failing to passing, the next test is written and development can continue.
> * Again, tests should be as simple as possible, only long enough to break the application in its current state. After the test is written, all development must focus on making the software pass the test.
>
> TDD proceeds in cycles which are usually called “red, green, refactor.” This cycle is usually done once for each unit test that you write. The cycle consists of three stages:
>
> * Red: Write a unit test that fails due to missing functionality in the software (since the color red usually denotes failure).
> * Green: Write code that fixes the issue by making the software pass the test (since the color green usually denotes success).
> * Refactor: Clean up the code base to account for the presence of this new code.

As with anything, there are no "universal truths" about software development, but these principles are *mostly* unchallenged - I promise, you will be happier, more successful and more productive, if you learn to follow these principles. 😊
</details>

**Comment by 132yse** [comment]
> Yes, definitely. Refs themselves can have direct effects on the DOM (or other global state) and these types of effects aren't complete without a clean-up cycle - just as useEffect would not be very useful if it didn't support clean-up.

If so, I need to refactor it again.

And about tests, I would like to comply with the tes, after we discuss the results, I will try to update the tests and make a report.

**Comment by 132yse** [comment]
@mindplay-dk Hello, I'm back. The current behavior is the same as that of preact, just as we discussed at https://github.com/preactjs/preact/issues/2052
![QQ图片20191120151053](https://user-images.githubusercontent.com/12951461/69216775-f4a32d00-0ba7-11ea-8df0-dd5b67a2bd82.png)
Thank you very much for your waiting

**Comment by mindplay-dk** [comment]
It's still not quite correct, but very close now - the only problem now, is there's an extra set of `null` events after the first render:

![image](https://user-images.githubusercontent.com/103348/69226285-2ef8d400-0b80-11ea-9102-930312400336.png)

Also (blue arrow) the order in which nested refs get dispatched is children-to-parents, compared with React/Preact which are parent-to-children. I don't know if this is very important, it might not be.

But the extra arrows are definitely important, since user code may be trying to clean up after effects that weren't dispatched yet.

From the [manual](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) section on callback refs:

> React will call the `ref` callback with the DOM element when the component mounts, and call it with `null` when it unmounts.

We're very close now though, and the [test](https://github.com/132yse/fre/compare/master...mindplay-dk:test-callback-refs) I proposed would almost pass.

(This is assuming you can resolve the timing issue with effect clean-up, which right now is causing most of the render-tests to break... as discussed, deferring by one frame is not the correct way to do this - for one, it makes it impossible to actually write a working test, and for another, you risk triggering new effects before the last round of effects have finished cleaning up, which could create conflicts.)

**Comment by 132yse** [comment]
I have fix the red arrow. the blued arrow in preact/react may be a stack. I think it may be not important. 
In the long time, it may be fixed

**Comment by mindplay-dk** [comment]
I've confirmed the fix, looks right. 👍

Let's keep this issue open until we have a test to prove it. (Blocked by #91)

**Comment by yisar** [comment]
We already have tests about refs [here](https://github.com/yisar/fre/blob/master/test/ref.test.js), I'll close it first.
